version: '3.0'
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.9.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - custom
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/pipelines:/usr/share/logstash/config/pipelines:ro
      - ./output:/usr/share/logstash/output

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.20-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - custom

networks:
  custom:
    driver: bridge